### ISSUE TITLE
Fix broken link

### ISSUE THREAD

**Issue by jhrcek** [shapr/shapr.github.io#2]
Hey, was just browsing through your blog and found a broken link on this page
https://shapr.github.io/posts/2022-04-11-smt-solvers-part-three.html

It links to Lindsey Kuper's course as 
http://composition.al/CSE290Q-2019-09/
But the correct URL seems to be 
https://decomposition.al/CSE290Q-2019-09/

**Comment by shapr** [comment]
Thank you for the bug report!
When Lindey's domain name had drama, I forgot to update the link.
I'll update it in a few hours.

**Comment by shapr** [comment]
I've updated the link, thanks for the bug report

**Comment by jhrcek** [comment]
Wasn't a big deal. But thanks to your blog a did a short and fun trip into SAT solving :smile:
